swagger: '2.0'
info:
  version: 1.0.0
  title: Access Control
  description: |
    The CANFAR access control web service.


    The following operations are available in the Access Control (AC) web service:


    - User Management
    - User Login
    - Who Am I (Logged-in user info)
    - Service Availability


    A CANFAR user can be identified in multiple ways, including:


    - Their distinguished name (DN) as described on their client certificate
    - Their CANFAR userID


    In the cases where clients of the web service need to identify a user through the REST API, either in the URL or in a posted document, it is done using two fields:


    idType - Describes the type of identity being provided in field userID. Accepted values of idType are:



      - x509 - Indicates value of userID is in DN format.



      - http - Indicates value of userID is in http-basic authorization userid
    format.


    id - The value identifying the user in the format specified by idType


    Group management and group search are provided by the Group Management Service (GMS), not this AC API.
basePath: /ac
paths:
  /users:
    get:
      description: |
        Lists basic public information about users in the service.
      tags:
        - Users
      schemes:
        - https
      produces:
        - text/xml
      responses:
        '200':
          description: Successful response
        '403':
          description: (forbidden) if the caller does not have permission
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
    put:
      description: |
        Request the user account in the user XML document in the HTTP PUT. This can take an arbitrary amount of time. If the account existed before but was deleted, this operation will reenable the account.
      tags:
        - Users
      schemes:
        - https
      consumes:
        - text/xml
      responses:
        '200':
          description: Successful response
        '409':
          description: 409 Conflict - If a user with the same name already exists.
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
  '/users/{userID}':
    get:
      description: |
        Get the user with userid {userID} of type {idType}. This operation supports an optional parameter 'detail', which can have values of display or identity. The detail parameter adjusts the amount type of user information that is returned.
      tags:
        - Users
      schemes:
        - https
      produces:
        - text/xml
      responses:
        '200':
          description: Successful response
        '404':
          description: '404 Not Found - If the user {userID} could not be found.'
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
      parameters:
        - name: detail
          in: query
          description: Set the level of detail
          required: false
          type: string
          enum:
            - display
            - identity
    delete:
      description: |
        DELETE the user with ID {userID}.
      tags:
        - Users
      schemes:
        - https
      responses:
        '200':
          description: Successful response
        '404':
          description: '404 Not Found - If the user {userID} could not be found.'
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
      parameters:
        - name: hard
          in: query
          description: 'If true, delete rather than deactive (operational use only)'
          required: false
          type: string
    post:
      description: |
        Modify the user with name {userID} according to the user XML document in the HTTP POST.
      tags:
        - Users
      schemes:
        - https
      consumes:
        - text/xml
      responses:
        '200':
          description: Successful response
        '404':
          description: '404 Not Found - If the user {userID} could not be found.'
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
    parameters:
      - name: userID
        in: path
        description: The ID of the user
        required: true
        type: string
      - name: idType
        in: query
        description: The type of userID
        required: true
        type: string
        enum:
          - http
          - x509
          - cadc
  /login:
    post:
      description: |
        Validate the userID and password combination. If the combination is valid this operation will return a cookie that can be used to enter any of these endpoints over HTTP.
      tags:
        - Users
      schemes:
        - https
      consumes:
        - text/xml
      responses:
        '200':
          description: Successful response
        '403':
          description: 403 Permission Denied - If the userID / pasword validation failed.
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
      parameters:
        - name: username
          in: query
          description: The username for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login
          required: true
          type: string
  /whoami:
    get:
      description: |
        Returns information about the authentication user.
      tags:
        - Users
      schemes:
        - https
      consumes:
        - text/xml
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
  /availability:
    get:
      tags:
        - Support Interfaces
      schemes:
        - https
      summary: VOSI Availability
      description: 'Indicates whether the service is operable and shows the reliability of the service for extended and scheduled requests. If the query parameter ''detail=min'' is used, a light weight heart beat test will be performed. The heart beat test returns status 200 if the service is available.'
      parameters:
        - name: detail
          in: query
          description: 'specifies heart beat to be used to check for availability of this service, the value ''min'' must be used, otherwise the full availability test will be performed'
          required: false
          type: string
      responses:
        '200':
          description: A VOSI availability document in XML.
        default:
          description: Unexpected error

