org.opencadc.ac.resourceID = {{ .Values.application.resourceID | required ".Values.application.resourceID is required" }}
{{- range .Values.application.readUsers }}
org.opencadc.ac.readUser = {{ . }}
{{- end }}
