ivo://ivoa.net/std/GMS#groups-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/GMS#search-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/GMS#search-1.0 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#users-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#reqs-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#login-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#modpass-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#resetpass-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/UMS#whoami-0.1 = {{ .Values.application.resourceID }}
ivo://ivoa.net/std/CDP#delegate-1.0 = ivo://cadc.nrc.ca/cred
ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://cadc.nrc.ca/cred
ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ .Values.application.registryURL | required ".Values.application.registryURL is required" }}
