tomcat.connector.connectionTimeout=180000
tomcat.connector.keepAliveTimeout=180000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName={{ include "ac.hostname" . }}
tomcat.connector.proxyPort=443
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
ca.nrc.cadc.util.Log4jInit.messageOnly=true
