openapi: 3.1.0
info:
  title: POSIX Mapper API
  version: "1.0"
  description: |
    The posix mapper API to discover local posix details
    for users and groups
servers:
- url: /example

tags:
    - name: VOSI Capabilities
    - name: POSIX Users
    - name: POSIX Groups

paths:
    /usermap:
        $ref: ./openapi/pm/posix-usermap.yaml

    /groupmap:
        $ref: ./openapi/pm/posix-groupmap.yaml

    /capabilities:
        $ref: ./openapi/vosi/vosi-capabilities.yaml
