CREATE TABLE <schema>.Users
(
    uid      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (uid)
);

CREATE TABLE <schema>.Groups
(
    gid       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    groupURI  VARCHAR(255),
    CONSTRAINT pk_groups PRIMARY KEY (gid)
);

create sequence <schema>.groups_gid_seq1
    start with 10000;

create sequence <schema>.users_uid_seq1
    start with 10000;
