CREATE TABLE <schema>.Users
(
    uid      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (uid)
);

CREATE TABLE <schema>.Groups
(
    gid       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    groupURI  VARCHAR(255) UNIQUE,
    CONSTRAINT pk_groups PRIMARY KEY (gid)
);

create sequence <schema>.groups_gid_seq1
    start with <gid_start>;

create sequence <schema>.users_uid_seq1
    start with <uid_start>;
