## commented out values are the defaults, shown as examples
## to customise behaviour, subclass the specified class and
## change the configuration here

## GroupPersistence implementation
ca.nrc.cadc.ac.server.GroupPersistence = org.opencadc.gms.GroupPersistenceImpl